name: M2 Mess Detector
on: [push, pull_request]

jobs:
  phpmd:
    name: M2 Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julienloizelet/github-actions-m2-crowdsec/magento-mess-detector@master
